### ISSUE TITLE
Crash to desktop when combined with Valkyrien Warfare

### ISSUE THREAD

**Issue by StarkRG** [maruohon/placementpreview#7]
Though I have a strong suspicion that the problem lies with VW, I'm also reporting the bug here for the sake of completeness.

[Full log](http://paste.ee/r/Kl6ca)

Specific error:
> java.lang.NullPointerException: Unexpected error
> 	at ValkyrienWarfareBase.PhysicsManagement.DimensionPhysObjectManager.getObjectManagingChunk(DimensionPhysObjectManager.java:68)
> 	at ValkyrienWarfareBase.PhysicsManagement.DimensionPhysObjectManager.getObjectManagingPos(DimensionPhysObjectManager.java:75)
> 	at ValkyrienWarfareBase.CoreMod.CallRunner.onPlaySound(CallRunner.java:344)
> 	at net.minecraft.client.entity.EntityPlayerSP.func_184185_a(EntityPlayerSP.java:552)
> 	at net.minecraft.entity.EntityLivingBase.func_184606_a_(EntityLivingBase.java:485)
> 	at net.minecraft.entity.player.EntityPlayer.func_184201_a(EntityPlayer.java:2189)
> 	at net.minecraft.entity.EntityLivingBase.func_184611_a(EntityLivingBase.java:1495)
> 	at fi.dy.masa.placementpreview.event.TickHandler.doUseAction(TickHandler.java:249)
> 	at fi.dy.masa.placementpreview.event.TickHandler.tryPlaceFakeBlocks(TickHandler.java:221)
> 	at fi.dy.masa.placementpreview.event.TickHandler.checkAndUpdateBlocks(TickHandler.java:185)
> 	at fi.dy.masa.placementpreview.event.TickHandler.onClientTick(TickHandler.java:90)
> 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_903_TickHandler_onClientTick_ClientTickEvent.invoke(.dynamic)
> 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
> 	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
> 	at net.minecraftforge.fml.common.FMLCommonHandler.onPostClientTick(FMLCommonHandler.java:344)
> 	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1851)
> 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
> 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
> 	at net.minecraft.client.main.Main.main(SourceFile:124)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
> 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:236)
> 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:297)
> 	at org.multimc.EntryPoint.listen(EntryPoint.java:162)
> 	at org.multimc.EntryPoint.main(EntryPoint.java:53)

**Comment by maruohon** [comment]
Seems like another bug in my fake player stuff...
